# Generated by Django 3.1.2 on 2023-01-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20230124_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='Article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='Tags',
            new_name='tags',
        ),
    ]
